---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: opencast-nginx-centos8
    image: quay.io/centos/centos:stream8
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: opencast-nginx-centos9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: opencast-nginx-debian
    image: docker.io/debian:stable
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: opencast-nginx-ubuntu
    image: docker.io/ubuntu:20.04
    pre_build_image: false
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
